/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppRecepcaoRouteImport } from './routes/app.recepcao'
import { Route as AppProfissionaisRouteImport } from './routes/app.profissionais'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppAssociadosRouteImport } from './routes/app.associados'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as PortalSlugProRouteImport } from './routes/portal.$slug.$pro'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublicMercadopagoCheckoutRouteImport } from './routes/api/public/mercadopago-checkout'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppRecepcaoRoute = AppRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppAssociadosRoute = AppAssociadosRouteImport.update({
  id: '/associados',
  path: '/associados',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const PortalSlugProRoute = PortalSlugProRouteImport.update({
  id: '/$pro',
  path: '/$pro',
  getParentRoute: () => PortalSlugRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoCheckoutRoute =
  ApiPublicMercadopagoCheckoutRouteImport.update({
    id: '/api/public/mercadopago-checkout',
    path: '/api/public/mercadopago-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/associados': typeof AppAssociadosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/portal/$slug': typeof PortalSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/mercadopago-checkout': typeof ApiPublicMercadopagoCheckoutRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/portal/$slug/$pro': typeof PortalSlugProRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/associados': typeof AppAssociadosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/portal/$slug': typeof PortalSlugRouteWithChildren
  '/app': typeof AppIndexRoute
  '/api/public/mercadopago-checkout': typeof ApiPublicMercadopagoCheckoutRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/portal/$slug/$pro': typeof PortalSlugProRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/associados': typeof AppAssociadosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/portal/$slug': typeof PortalSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/mercadopago-checkout': typeof ApiPublicMercadopagoCheckoutRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/portal/$slug/$pro': typeof PortalSlugProRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/upgrade'
    | '/app/agenda'
    | '/app/associados'
    | '/app/financeiro'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/whatsapp'
    | '/portal/$slug'
    | '/app/'
    | '/api/public/mercadopago-checkout'
    | '/api/public/mercadopago-webhook'
    | '/portal/$slug/$pro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/upgrade'
    | '/app/agenda'
    | '/app/associados'
    | '/app/financeiro'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/whatsapp'
    | '/portal/$slug'
    | '/app'
    | '/api/public/mercadopago-checkout'
    | '/api/public/mercadopago-webhook'
    | '/portal/$slug/$pro'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/upgrade'
    | '/app/agenda'
    | '/app/associados'
    | '/app/financeiro'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/whatsapp'
    | '/portal/$slug'
    | '/app/'
    | '/api/public/mercadopago-checkout'
    | '/api/public/mercadopago-webhook'
    | '/portal/$slug/$pro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  UpgradeRoute: typeof UpgradeRoute
  PortalSlugRoute: typeof PortalSlugRouteWithChildren
  ApiPublicMercadopagoCheckoutRoute: typeof ApiPublicMercadopagoCheckoutRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recepcao': {
      id: '/app/recepcao'
      path: '/recepcao'
      fullPath: '/app/recepcao'
      preLoaderRoute: typeof AppRecepcaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profissionais': {
      id: '/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/associados': {
      id: '/app/associados'
      path: '/associados'
      fullPath: '/app/associados'
      preLoaderRoute: typeof AppAssociadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/$slug/$pro': {
      id: '/portal/$slug/$pro'
      path: '/$pro'
      fullPath: '/portal/$slug/$pro'
      preLoaderRoute: typeof PortalSlugProRouteImport
      parentRoute: typeof PortalSlugRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-checkout': {
      id: '/api/public/mercadopago-checkout'
      path: '/api/public/mercadopago-checkout'
      fullPath: '/api/public/mercadopago-checkout'
      preLoaderRoute: typeof ApiPublicMercadopagoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAssociadosRoute: typeof AppAssociadosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppRecepcaoRoute: typeof AppRecepcaoRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAssociadosRoute: AppAssociadosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppRecepcaoRoute: AppRecepcaoRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalSlugRouteChildren {
  PortalSlugProRoute: typeof PortalSlugProRoute
}

const PortalSlugRouteChildren: PortalSlugRouteChildren = {
  PortalSlugProRoute: PortalSlugProRoute,
}

const PortalSlugRouteWithChildren = PortalSlugRoute._addFileChildren(
  PortalSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  UpgradeRoute: UpgradeRoute,
  PortalSlugRoute: PortalSlugRouteWithChildren,
  ApiPublicMercadopagoCheckoutRoute: ApiPublicMercadopagoCheckoutRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
