/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppRecepcaoRouteImport } from './routes/app.recepcao'
import { Route as AppProfissionaisRouteImport } from './routes/app.profissionais'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppAssociadosRouteImport } from './routes/app.associados'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppRecepcaoRoute = AppRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppAssociadosRoute = AppAssociadosRouteImport.update({
  id: '/associados',
  path: '/associados',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/associados': typeof AppAssociadosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/associados': typeof AppAssociadosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/associados': typeof AppAssociadosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/associados'
    | '/app/financeiro'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/whatsapp'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/associados'
    | '/app/financeiro'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/whatsapp'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/associados'
    | '/app/financeiro'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/whatsapp'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recepcao': {
      id: '/app/recepcao'
      path: '/recepcao'
      fullPath: '/app/recepcao'
      preLoaderRoute: typeof AppRecepcaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profissionais': {
      id: '/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/associados': {
      id: '/app/associados'
      path: '/associados'
      fullPath: '/app/associados'
      preLoaderRoute: typeof AppAssociadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAssociadosRoute: typeof AppAssociadosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppRecepcaoRoute: typeof AppRecepcaoRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAssociadosRoute: AppAssociadosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppRecepcaoRoute: AppRecepcaoRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
